apiVersion: apps/v1
kind: Deployment
metadata:
  name: safe-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: safe-monitor
  template:
    metadata:
      labels:
        app: safe-monitor
    spec:
      containers:
      - name: monitor
        image: wshino/safe-wallet-monitor
        env:
        - name: NETWORK
          valueFrom:
            configMapKeyRef:
              name: safe-monitor-config
              key: NETWORK
        - name: MONITORED_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: safe-monitor-config
              key: MONITORED_ADDRESS
        - name: ALCHEMY_API_KEY
          valueFrom:
            secretKeyRef:
              name: safe-monitor-secrets
              key: ALCHEMY_API_KEY
        - name: SLACK_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: safe-monitor-secrets
              key: SLACK_WEBHOOK_URL